typography_spectrum: 0.7102580601349473
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9734015914145857
  lightness: 0.3931538672186434
  saturation: 0.6306907047983259
  rhythmicContrast: 0.201296744402498
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5470126713626087
analytics:
  google: null
  facebook: null
  twitter: null
name: OurComputerGuy
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: welcome
description: medical solutions for everyone
purpose: []
